### ISSUE TITLE
[BUG]  ithub login broken on brave browser...

### ISSUE THREAD

**Issue by tracure1337** [JP1016/Codekeep-Issues#7]
Github login broken on brave browser...other sites work with my GH login

**Comment by PJijin** [comment]
We have fixed the issue. 

Please check again: https://codekeep.io/home/login 

Thank You 😊

**Comment by tracure1337** [comment]
Excellent. 🚀  Can you elaborate on the fix? 

I'd like to share your solution for other projects where I  noticed similar behavior.
