### ISSUE TITLE
[BUG] Light and dark mode icons are the wrong way around

### ISSUE THREAD

**Issue by nblackburn** [JP1016/Codekeep-Issues#9]
**Describe the bug**
The dark/light mode icons are the wrong way around.

**To Reproduce**
1.  In dark mode, clicking the "moon" icon activates light mode.
2. In light mode, clicking the "sun" icon activates dark mode.

**Expected behavior**
Clicking the "sun" icon should activate light mode and clicking the "moon" should activate dark mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/2931085/104851765-e1483a80-58ee-11eb-80c0-48c5e5016b2f.png)
![image](https://user-images.githubusercontent.com/2931085/104851780-f02eed00-58ee-11eb-9ee6-0c8249996042.png)

**Comment by JP1016** [comment]
Thanks for reporting @nblackburn , fix deployed :-)
